# Site settings
title: Lucas Vittor Blog # site title
description: >- # site description
  The place where I share my learnings.
lang: en-US # default lang
timezone: America/Argentina/Buenos_Aires # set your timezone: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/lvvittor/lvvittor.github.io # site repo [optional]
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Lucas Vittor # author name
  bio: >- # tell to the world
    The place where I share my learnings.
  username: lvvittor # general username
  github: lvvittor # GitHub username
  twitter: lvvittor # Twitter username
  facebook: facebook_username # facebook username
  email: lvvittor@gmail.com # email address
  avatar: /assets/img/avatar.png # change with your own avatar

# URL settings
url: "https://www.lucasvittor.com"
baseurl:
permalink: /:title/
google_analytics: UA-213772369-1
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: true

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - LICENSES 
  - Gemfile
  - Gemfile.lock
  - COPYING
  - Makefile
  - README.md
  - node_modules
  - CONTRIBUTING.md
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
  - jekyll-seo-tag
